namespace Sitecore.Glimpse
{
    public enum DataKey
    {
        Item,
        Goals,
        Profiles,
        LastPages,
        Campaign,
        TrafficType,
        EngagementValue,
        IsNewVisitor,
        Site,
        Database,
        User,
        Domain,
        Request,
        ItemTemplate,
        Device,
        Diagnostics,
        ItemVisualization,
        Language,
        Culture,
        Services,
        License,
        UserList,
        VersionInfo
    }
}